FROM cmdb-base:dev
COPY services/ipam/pyproject.toml ./services/ipam/pyproject.toml
RUN uv sync --frozen --package cmdb-ipam
EXPOSE 8000
CMD ["uv", "run", "--package", "cmdb-ipam", "uvicorn", "ipam.interface.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
