FROM cmdb-base:dev
COPY services/event/pyproject.toml ./services/event/pyproject.toml
RUN uv sync --frozen --package cmdb-event
EXPOSE 8000
CMD ["uv", "run", "--package", "cmdb-event", "uvicorn", "event.interface.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
